name: Test
on:
  pull_request_target:
  push:
    branches-ignore: 
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions: {}
jobs:
  authorize:
    environment:
      ${{ (github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository) &&
      'External' || 'Internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ✓
  test-job:
    needs: authorize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          ref: ${{github.event.pull_request.head.sha || github.ref}}
          persist-credentials: 'false' #By default, actions/checkout persists GIT credentials, we do not need this
      - run: printenv EXTERNAL_SECRET
        env:
          EXAMPLE: ${{ secrets.EXTERNAL_SECRET }}
      - run: printenv INTERNAL_SECRET
        env:
          EXAMPLE: ${{ secrets.INTERNAL_SECRET }}
